### ISSUE TITLE
Generated QR code image has padding on the right and bottom

### ISSUE THREAD

**Issue by wanyx2015** [naimmalek/an-qrcode#1] opened 2020-06-11 02:06 UTC
I wanted to make image center horizontally but only finding out the image is larger than the qr code and the qr code is on the top left of the image, leaving some blank padding on the right and bottom.

**Comment by naimmalek** [comment] 2020-06-11 02:59
@wanyx2015 did you added size input property?

**Comment by wanyx2015** [comment] 2020-06-11 03:43
Yes I used the size property.

Just now I checked the image again, I am using Firefox, the image shows blank padding. But on Chrome, it does not.

Here is the data url, you can paste it on Firefox address bar to have a look.

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAJsElEQVR4nO2TUa4kMQwC5/6X3r1Aj0RPETvoUZL/nIBx8vlXyhCfRLZDK3+H7bf+E9uhlb/D9lv/ie3Qyt9h+63/xHZo5e+w/dZ/4ssg19SEP7eGep+b7V0JGeQRGvTVGup9brZ3JWSQR2jQV2uo97nZ3pWQQR6hQV+tod7nZntXQgZ5hAZ9tYZ6n5vtXQkZ5LG1TKL71Oc+S8qt687PzYsM8iADu1F1n/rcZ0m5dd35uXmRQR5kYDeq7lOf+ywpt647PzcvMsiDDOxG1X3qc58l5dZ15+fmRQZ5kIHdqLpPfe6zpNy67vzcvMggDzjw8UdE+tyeia7bC8llUTeP0KD7QUAui7p5hAbdDwJyWdTNIzTofhCQy6JuHqFB94OAXBZ180gMmnghkHndXlR/7jmgbh6JQRMvBDKv24vqzz0H1M0jMWjihUDmdXtR/bnngLp5JAZNvBDIvG4vqj/3HFA3j8SgiRcCmdftRfXnngPq5hEatFVjwrN7DuJlcW95hAbdDwK8LO4tj9Cg+0GAl8W95REadD8I8LK4tzxCg+4HAV4W95YHGdgN0X06u3XfhBfS5+aFvzzIwG6I7tPZrfsmvJA+Ny/85UEGdkN0n85u3TfhhfS5eeEvDzKwG6L7dHbrvgkvpM/NC395kIHdEN2ns1v3TXghfW5e+MtDHXir4EL+fN9le8sjNOj2iX2X7S2P0KDbJ/Zdtrc8QoNun9h32d7yCA26fWLfZXvL43GSQD5LH049S+4jGjdx7hUfZDs0F59+kOs594oPsh2ai08/yPWce8UH2Q7Nxacf5HrOveKDbIfm4tMPcj3nXvFBvgyysnRSxJ97DnKf++xlGeRBAnSHSor4c89B7nOfvSyDPEiA7lBJEX/uOch97rOXZZAHCdAdKinizz0Huc999rIM8iABukMlRfy55yD3uc9elkEeE8EQiIZ7DvdZ97xuz25/5J2uQUJ9KjdEwz2H+6x7Xrdntz/yTtcgoT6VG6LhnsN91j2v27PbH3mna5BQn8oN0XDP4T7rntft2e2PvNM1SKhP5YZouOdwn3XP6/bs9kfe6Rq/hP42rKc+tYgXct+WBvHi9nwgvzzgwP0g/SBvPOcBB+4H6Qd54zkPOHA/SD/IG895wIH7QfpB3njOwx2+G+KF1IQXdy5bGbw4m4caAukjEC+kJry4c9nK4MXZPNQQSB+BeCE14cWdy1YGL87moYZA+gjEC6kJL+5ctjJ4cTYPNQTSRyBeSE14ceeylcGLs3m4l7S1TNWL258bouvO4IBGHvJ05lAniszh1nB7Uc8S3QMaecjTmUOdKDKHW8PtRT1LdA9o5CFPZw51osgcbg23F/Us0T2gkYc8nTnUiSJzuDXcXtSzRPeARh5qCE9FwnffR/rcTOiqmZJyz4sf6wYkfPcyDyykH6QfhEHCdy/zwEL6QfpBGCR89zIPLKQfpB+EQcJ3L/PAQvpB+kEYroW9DVAt9b4tXfWs+z63LuGF5zxQMiBAtdT7tnTVs+773LqEF57zQMmAANVS79vSVc+673PrEl54zgMlAwJUS71vS1c9677PrUt44TkPlAwIUC31vi1d9az7Prcu4YXnPNSBJ8q9kNtnI30TmR6YN4/bH5Hqb+shkNlI30SmB+bN4/ZHpPrbeghkNtI3kemBefO4/RGp/rYeApmN9E1kemDePG5/RKq/rYdAZiN9E5kemDcPOUEQtPusW4Pct0Wo5zwOhNAPMkCo5zwOhNAPMkCo5zwOhNAPMkCo5zwOhNAPMkCo5zy+DGJ9RFtnEzXc2RONA7p5kADJQibOJmq4sycaB3TzIAGShUycTdRwZ080DujmQQIkC5k4m6jhzp5oHNDNgwRIFjJxNlHDnT3ROKCbhzvAp5rQuF3X7cWNe44vfXmoA5Oa0Lhd1+3FjXuOL315qAOTmtC4XdftxY17ji99eagDk5rQuF3X7cWNe44vfXmoA5Oa0Lhd1+3FjXuOL315qAOrNbGQCc+kb0vjpvoyRx4Tj408DnIf8Uz6tjRuqi9z5DHx2MjjIPcRz6RvS+Om+jJHHhOPjTwOch/xTPq2NG6qL3PkMfHYyOMg9xHPpG9L46b6Mkce7qUTVA23P3LfhGf1LCn3bF/68nAvk6BquP2R+yY8q2dJuWf70peHe5kEVcPtj9w34Vk9S8o925e+PNzLJKgabn/kvgnP6llS7tm+9OXhXiZB1XD7I/dNeFbPknLP9qUvj8dJLuez9NjU+9x96lkVch88m8cvAW/z6Qf5LbiXXg6czeOXgLf59IP8FtxLLwfO5vFLwNt8+kF+C+6llwNn8/gl4G0+/SC/BffSy4GzeaghbBVZ0u1eiOcJL27UN3kVaoBbpfqbmMPthXie8OJGfZNXoQa4Vaq/iTncXojnCS9u1Dd5FWqAW6X6m5jD7YV4nvDiRn2TV6EGuFWqv4k53F6I5wkvbtQ3eRWXBXj84ZP7bpptwsuBs3m4QyCouk99apH7bpptwsuBs3m4QyCouk99apH7bpptwsuBs3m4QyCouk99apH7bpptwsuBs3m4QyCouk99apH7bpptwsuBs3mQEJ761JrQfbG44/e5vUyUOyvhOd4HWfBTn1oTuioT97m9TJQ7K+E53gdZ8FOfWhO6KhP3ub1MlDsr4TneB1nwU59aE7oqE/e5vUyUOyvhOd4HWfBTn1oTuioT97m9TJQ7K+E53gdZ8FOfWhO6bs8TNTGvmxde8oAD94P0g/SDfGnrB+kHeaUhPMf7gAP3g/SD9IN8aesH6Qd5pSE8x/uAA698EBVynzsDouvOdHG/eajBbC2TQO5zZ0B03Zku7jcPNZitZRLIfe4MiK4708X95qEGs7VMArnPnQHRdWe6uN881GC2lkkg97kzILruTBf3m4cazAQTuk8aam15ViFzqPfBvjzIwG4mdJ801NryrELmUO+DfXmQgd1M6D5pqLXlWYXMod4H+/IgA7uZ0H3SUGvLswqZQ70P9uVBBnYzofukodaWZxUyh3of7MuDBD1Rbn8Tj2NrNjLvBOqbvIovg1xTbn8vltkPYkZ9k1fxZZBryu3vxTL7Qcyob/IqvgxyTbn9vVhmP4gZ9U1exZdBrim3vxfL7Acxo77Jq9gOrfwdtt/6T2yHVv4O22/9J7ZDK3+H7bf+E9uhlb/D9lv/ie3Qyt9h+62XUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFL+EP8BAmCooZgc5VEAAAAASUVORK5CYII=

**Comment by naimmalek** [comment] 2020-06-11 03:51
@wanyx2015 Yes got that, fixing in progress, will be fixed in release version 1.0.4 soon.

**Comment by wanyx2015** [comment] 2020-06-11 03:58
Thanks in advance!

**Comment by naimmalek** [comment] 2020-06-11 05:18
@wanyx2015 its fixed and released in version 1.0.4.

**Comment by wanyx2015** [comment] 2020-06-11 05:47
@naimmalek It's working great! Now the extra padding is removed.

I want to confirm one more thing: I set the size to 200, and the actual image size is 140. So size of 300 get an actual 210 width image. Is this by design or I missed something?

**Comment by naimmalek** [comment] 2020-06-11 05:52
you can set it by design throgh your css. Closing this issue as its fixed.

**Closed as completed by naimmalek** 2020-06-11 05:52 UTC

**Comment by wanyx2015** [comment] 2020-06-11 05:59
Thank you very much!
